---

- name: Run show commands on routers
  hosts: all

  tasks:

    - name: Get interface info
      cli_command: 
        command: "{{interface_info}}"
      register: command_output

    - name: Debug vars
      debug:
        var: command_output.stdout_lines
