---

- name: Configure with Jinja tempalte
  hosts: all
  gather_facts: true

  tasks:

    - name: Debug var
      debug:
        var: ansible_net_all_ipv4_addresses

    - name: Configure OSPF
      cli_config:
        config: "{{ lookup('template', 'templates/{{ansible_network_os}}_ospf.j2')}}"
