---
# vars file for spine
  l3_interfaces:
    - interface: Ethernet1/1
    - interface: Ethernet1/2
    - interface: Ethernet1/3
    - interface: loopback0
    - interface: loopback1

  l3_phy_interfaces:
    - interface: Ethernet1/1
    - interface: Ethernet1/2
    - interface: Ethernet1/3
  
  asn: 65000

  bgp_neighbors:
    - { remote_as: 65000, neighbor: 192.168.0.8, update_source: loopback0 }
    - { remote_as: 65000, neighbor: 192.168.0.10, update_source: loopback0 }
    - { remote_as: 65000, neighbor: 192.168.0.11, update_source: loopback0 }

  s1_loopback: 192.168.0.6
  s2_loopback: 192.168.0.7

  rp_address: 192.168.0.100
