---

- name: Run show commands on routers
  hosts: 192.168.106.216
  gather_facts: false

  tasks:


    - name: run show ip int br
      ios_command:
        commands: show ip int br
      register: sh_ip_int_br_result

    - name: Debug registered var
      debug:
        msg: "IP addresss is not found"
      when: "'4.4.4.4' not in sh_ip_int_br_result.stdout[0]"
