---
# tasks file for core_sw

  - name: Configure hostnames
    cisco.ios.ios_hostname:
      config:
        hostname: "{{ inventory_hostname }}"
      state: overridden
    tags: hostname

  - name: Configure VLANS
    cisco.ios.ios_vlans:
      config:
        - name: "{{ item.name  }}"
          vlan_id: "{{ item.vlan }}"
          state: active
          shutdown: disabled
      state: merged
    with_items: "{{ vlans  }}"
    tags: vlans

  - name: Create LAG ports
    cisco.ios.ios_lag_interfaces:
      config:
        - name: "{{ item.name }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
      state: merged
    with_items: "{{ lag }}"
    tags: lag

  - name: Configure trunk ports
    cisco.ios.ios_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          trunk:
            allowed_vlans: "{{ item.allowed_vlans }}"
            encapsulation: dot1q
            native_vlan: "{{ item.native_vlan }}"
      state: merged
    with_items: "{{ trunks }}"
    tags: trunk


  - name: Configure mode trunk for ports
    cisco.ios.ios_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          mode: trunk
      state: merged
    with_items: "{{ trunks }}"
    tags: trunk


  - name: Enable L2 interfaces
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ item.interface }}"
          enabled: true
      state: merged
    with_items: "{{ lag }}"
    tags: l2_intf
  
  
  - name: Configure L3 interfaces
    cisco.ios.ios_l3_interfaces:
     config:
       - name: "{{ item.interface }}"
         ipv4:
           - address: "{{ item.ip_add }}"
     state: merged
    with_items: "{{ l3_interfaces }}"
    tags: l3_intf


  - name: Enable L3 interfaces
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ item.interface }}"
          enabled: true
      state: merged
    with_items: "{{ l3_interfaces }}"
    tags: l3_intf


  - name: Configure STP
    cisco.ios.ios_spanning_tree:
      config:
        mode: "rapid-pvst"
        backbonefast: true
        portfast:
          default: true
        priority:
          - value: 4096
            vlan_list: 1-4094
    tags: stp

