---

- name: Configure VPN
  hosts: isp1,isp2

  vars:
    wan_ip_1: 192.168.106.216
    wan_ip_2: 192.168.106.215
    tun_ip_1: 10.0.1.1 255.255.255.252
    tun_ip_2: 10.0.1.2 255.255.255.252

  tasks:

    - name: Collect facts
      ios_facts:
        gather_subset:
          - "!hardware"

    - name: Collect current tunnel numbers
      set_fact:
        tun_num: "{{ ansible_net_config | regex_findall('interface Tunnel(.*)') }}"


    - debug: var=tun_num

    - debug: var=hostvars

    - name: Generate VPN config of router 1
      template:
        src: templates/ios_vpn1.j2
        dest: configs/result1.txt
      when: wan_ip_1 in ansible_net_all_ipv4_addresses

    - name: Generate VPN config for router 2
      template:
        src: templates/ios_vpn2.j2
        dest: configs/result2.txt
      when: wan_ip_2 in ansible_net_all_ipv4_addresses

