---
# tasks file for spine
  - name: Configure hostname
    nxos_config:
      lines: hostname {{ hostname }}
    tags: hostname
  
# task to configure bgp neighbor to all leaf switches
  - name: Enable BGP
    nxos_feature:
      feature: bgp
      state: enabled
    tags: bgp

  - name: Enable OSPF
    nxos_feature:
      feature: ospf
      state: enabled
    tags: ospf

  - name: Configure BGP AF
    cisco.nxos.nxos_bgp_address_family:
      config:
        as_number: "{{ asn }}"
        address_family:
          - afi: ipv4
            safi: unicast
    tags: bgp
    
  - name: Configure BGP AS and peers
    cisco.nxos.nxos_bgp_global:
      config:
        as_number: "{{ asn }}"
        router_id: "{{ router_id }}"
        neighbors:
          - neighbor_address: "{{ item.neighbor }}"
            remote_as: "{{ item.remote_as }}"
            update_source: "{{ item.update_source }}"
    with_items: "{{ bgp_neighbors }}"
    tags: bgp
 
  - name: Configure iBGP neighbor AF
    cisco.nxos.nxos_bgp_neighbor_address_family:
      config:
        as_number: "{{ asn }}"
        neighbors:
          - neighbor_address: "{{ item.neighbor }}"
            address_family:
            - afi: ipv4
              safi: unicast
              send_community:
                both: True
              route_reflector_client: True
    with_items: "{{ bgp_neighbors }}"
    tags: bgp   
  
  - name: Create Loopback interfaces
    nxos_interfaces:
      config:
      - name: "{{ item.interface }}"
        description: "{{ item.interface }} interface"
        enabled: True
    with_items: "{{ loopbacks }}"
    tags: ip
  
  - name: Configure IP Addresses for loopbacks
    nxos_l3_interfaces:
      config:
      - name: "{{ item.interface }}"
        ipv4: 
        - address: "{{ item.addr }}/{{ item.mask }}"
    with_items: "{{ loopbacks }}"
    tags: ip

 
  - name: Enable L3 physical interfaces
    nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          enabled: True
          mtu: 9216
          mode: layer3
    with_items: "{{ l3_phy_interfaces }}"
    tags: ip
  
  - name: Configure IP Unnambered on Physical interfaces
    nxos_config:
      lines:
        - medium p2p
        - ip unnumbered loopback 0
      parents:
        - "interface {{ item.interface }}"
    with_items: "{{ l3_phy_interfaces }}"
    tags: ip

  - name: Enable OSPF process
    nxos_ospfv2:
      config:
        processes:
          - process_id: 1
    tags: ospf

  - name: Enable OSPF on L3 interfaces
    cisco.nxos.nxos_ospf_interfaces:
      config:
        - name: "{{ item.interface }}"
          address_family:
            - afi: ipv4
              processes:
              - process_id: 1
                area:
                  area_id: 0.0.0.0
    with_items: "{{ l3_interfaces }}"
    tags: ospf

  - name: Enable PIM
    nxos_feature:
      feature: pim
      state: enabled
    tags: multicast

  - name: Configure PIM on L3 interfaces
    nxos_pim_interface:
      interface: "{{ item.interface }}"
      sparse: true
    with_items: "{{ l3_interfaces }}"
    tags: multicast

  - name: configure PIM RP
    nxos_pim_rp_address:
      rp_address: "{{ rp_address }}"
    tags: multicast

  - name: Configure Anycast RP
    nxos_config:
      lines:
        - "ip pim anycast-rp {{ rp_address }} {{ s1_loopback }}"
        - "ip pim anycast-rp {{ rp_address }} {{ s2_loopback }}"
    tags: multicast

# Configure vxlan fabric
  
  - name: Enable VXLAN feature
    nxos_feature:
      feature: nv overlay
      state: enabled
    tags: vxlan

  - name: Enable NV Overlay
    nxos_evpn_global:
      nv_overlay_evpn: true
    tags: vxlan

# Configure BGP EVPN

  - name: Configure BGP EVPN AF
    cisco.nxos.nxos_bgp_address_family:
      config:
        as_number: "{{ asn }}"
        address_family:
          - afi: l2vpn
            safi: evpn
    tags: evpn
  
  - name: Configure iBGP neighbor EVPN AF
    cisco.nxos.nxos_bgp_neighbor_address_family:
      config:
        as_number: "{{ asn }}"
        neighbors:
          - neighbor_address: "{{ item.neighbor }}"
            address_family:
            - afi: l2vpn
              safi: evpn
              send_community:
                both: True
              route_reflector_client: True
    with_items: "{{ bgp_neighbors }}"
    tags: evpn

# Save Configuration

  - name: SAVE CONFIG
    nxos_config:
      save_when: always
    tags: save

