---
# vars file for core_sw
  lag:
    - {name: Port-channel10, interface: Eth0/0}
    - {name: Port-channel20, interface: Eth0/1} 
    - {name: Port-channel30, interface: Eth0/2}
    - {name: Port-channel40, interface: Eth0/3} 
    - {name: Port-channel48, interface: Eth1/2}
    - {name: Port-channel48, interface: Eth1/3}
    
    
  trunks:
    - {interface: Port-channel10, allowed_vlans: "10,20,30", native_vlan: 1}
    - {interface: Port-channel20, allowed_vlans: "10,20,30", native_vlan: 1}
    - {interface: Port-channel30, allowed_vlans: "10,20,30", native_vlan: 1}
    - {interface: Port-channel40, allowed_vlans: "10,20,30", native_vlan: 1}
    - {interface: Port-channel48, allowed_vlans: "10,20,30", native_vlan: 1}


  vlans:
    - { name: FINANCE_VL10, vlan: 10}
    - { name: IT_DEPART_VL20, vlan: 20}
    - { name: PROD_VL30, vlan: 30}
    - { name: UNUSED, vlan: 999}


  l3_interfaces:
    - { interface: Vlan10, ip_add: 10.1.110.1/24 }
    - { interface: Vlan20, ip_add: 10.1.20.1/24 }
    - { interface: Vlan30, ip_add: 10.1.30.1/24 }
